## Directory tree structure for sys_mgmt  
##
#
# [ansadm@xyz  ansible]$ cd /etc/ansible/ 
#
# [ansadm@server1 ansible]$ tree 
#
# . 
#
# ├── ansible.cfg 
#
# ├── hosts 
#
# ├── hosts_orig 
#
# └── sys_mgmt 
#
#    ├── group_vars 
#
#    │   ├── user_create_orig.yml 
#
#    │   ├── user_create_var.yml 
#
#    │   ├── user_remove_orig.yml 
#
#    │   ├── user_remove_var.yml 
#
#    │   ├── user_search_orig.yml 
#
#    │   └── user_search_var.yml 
#
#    ├── hosts 
#
#    ├── playbook_usermgmt.yml 
#
#    ├── roles 
#
#    │   └── user_mgmt 
#
#    │       └── tasks 
#
#    │           └── main.yml 
#
#    └── script_usrmgmt.sh 
#
#  
#  
#
#----------------------------------------------------------------------------- 
#
## Inventory File 
##
#  
#
# [ansadm@server1 ansible]$ cat sys_mgmt/hosts
[localserver]
localhost       ansible_connection=local
#
#
#  
#
#----------------------------------------------------------------------------- 
#
# Bash Script  
#
#  
#
# [ansadm@server1 ansible]$ cat sys_mgmt/script_usrmgmt.sh 
#!/bin/bash
GROUP_VAR_PATH="/etc/ansible/sys_mgmt/group_vars"
SYS_MGMT_PATH="/etc/ansible/sys_mgmt"

while true 
do
        echo -e "Please select from below tasks \n"
        echo -e "1. Add a user \n"
        echo -e "2. Delete a user \n"
        echo -e "3. Search a user \n"
        echo -e "0. Exit \n"
        read choice

case $choice in 
        0)
        break
        ;;

        1)
        echo -e 'Enter user name which needs to be created'
        read newuser_name

        echo -e 'Enter user id for user' 
        read newuser_id

        echo -e 'Enter comments' 
        read newuser_comments

        echo -e 'Enter shell'
        read newuser_shell


        ## modifying user creation variable file as per the requirement 
        cat $GROUP_VAR_PATH/user_create_orig.yml | sed "s/usrname/$newuser_name/g" | sed "s/usrid/$newuser_id/g" | sed "s/cmts/$newuser_comments/g" | sed "s/usrshell/$newuser_shell/g" > $GROUP_VAR_PATH/user_create_var.yml

        #Running ansible playbook
        /bin/ansible-playbook $SYS_MGMT_PATH/playbook_usermgmt.yml -i $SYS_MGMT_PATH/hosts -b  -t user_create
        ;;

        2) 
        echo -e 'Enter user name which needs to be deleted'
        read olduser_name

        cat $GROUP_VAR_PATH/user_remove_orig.yml | sed "s/usrname/$olduser_name/g"  > $GROUP_VAR_PATH/user_remove_var.yml

        #Running ansible playbook 
        /bin/ansible-playbook $SYS_MGMT_PATH/playbook_usermgmt.yml -i $SYS_MGMT_PATH/hosts -b  -t user_delete

        #sleep 4 

        ;; 

  

        3) 

        echo -e 'Enter user name which needs to be searched' 

        read user_name 

  

        cat $GROUP_VAR_PATH/user_search_orig.yml | sed "s/usrname/$user_name/g"  > $GROUP_VAR_PATH/user_search_var.yml 

  

        #Running ansible playbook 

        /bin/ansible-playbook $SYS_MGMT_PATH/playbook_usermgmt.yml -i $SYS_MGMT_PATH/hosts  -t user_search 

#       sleep 4 

        ;; 

  

        *) 

        echo -e "Wrong Choice !!!! \n" 

        read dummy 

        continue 

        ;; 

esac 

  

done 

  

[ansadm@server1 ansible]$ 

  

----------------------------------------------------------------------------- 

Playbook for user management 

  

[ansadm@server1 ansible]$ cat sys_mgmt/playbook_usermgmt.yml 

--- 

- name: User Management playbook 

  hosts: localserver 

  user: ansadm 

  become: yes 

  become_method: sudo 

  vars_files: 

     - group_vars/user_create_var.yml 

     - group_vars/user_remove_var.yml 

     - group_vars/user_search_var.yml 

  

  roles: 

    - user_mgmt 

[ansadm@server1 ansible]$ 

  

----------------------------------------------------------------------------- 

Task inside the role 

  

[ansadm@server1 ansible]$ cat sys_mgmt/roles/user_mgmt/tasks/main.yml 

--- 

  

### This task is to search a user 

- name: Checking existence of user {{ newusername }}.... 

  shell: grep "^{{ newusername }}:" /etc/passwd 

  ignore_errors: yes 

  register: user_exist 

  tags: 

    - user_search 

    - user_create 

- debug: 

     msg: > 

        "User {{ newusername }} already exists on {{ ansible_hostname }}" 

  when: user_exist.rc == 0 

  tags: 

    - user_search 

    - user_create 

- debug: 

     msg: > 

       "User {{ newusername }} doesn't exist on {{ ansible_hostname }}" 

  when: user_exist.rc !=0 

  tags: 

   - user_search 

   - user_create 

  

### This task is to add a user 

  

- name: Adding user {{ newusername }}...... 

  user: 

   name={{ newusername }} 

   uid={{ newuserid }} 

  when: user_exist.rc !=0 

  register: usercreation 

  tags: user_create 

- debug: 

     msg: > 

        "User {{ newusername }} has been created on {{ ansible_hostname }}" 

  when: usercreation.changed 

  tags: user_create 

  

  

### This task is to remove a user 

  

- name: Removing user {{ oldusername }}...... 

  user: 

    name={{ oldusername }} 

    state=absent 

    remove=yes 

  register: userremoval 

  tags: user_delete 

- debug: 

     msg: > 

        "User {{ oldusername }} has been removed from {{ ansible_hostname }}" 

  when: userremoval.changed 

  tags: user_delete 

[ansadm@server1 ansible]$ 

  

----------------------------------------------------------------------------- 

Variable file 

  

[ansadm@server1  ansible]$ cat sys_mgmt/group_vars/user_create_orig.yml 

--- 

## variables for user creation 

  newuserid: usrid 

  newusername: usrname 

  newusercomments: cmts 

  newusershell: usrshell 

[ansadm@server1 ansible]$ cat sys_mgmt/group_vars/user_create_var.yml 

--- 

## variables for user creation 

  newuserid: 

  newusername: lalit 

  newusercomments: 

  newusershell: 

[ansadm@server1 ansible]$ cat sys_mgmt/group_vars/user_remove_orig.yml 

--- 

## variables for user creation 

  oldusername: usrname 

[ansadm@server1 ansible]$ cat sys_mgmt/group_vars/user_remove_var.yml 

--- 

## variables for user creation 

  oldusername: lalit 

[ansadm@server1 ansible]$ cat sys_mgmt/group_vars/user_search_orig.yml 

--- 

## variables for user 

  newusername: usrname 

[ansadm@server1 ansible]$ cat sys_mgmt/group_vars/user_search_var.yml 

--- 

## variables for user 

  newusername: lalit 

 
