#### $ cat playbook_historytimestamp.yaml
---
- name: playbook - Enable time stamp in history comamnd
 # hosts: servergroup
  hosts: all
  become: yes

  tasks:
    - name: copying history time script file to remote server's /etc/profile.d/ ...
      copy:
        src: /etc/ansible/history_timestamp/history_timestamp.sh
        dest: /etc/profile.d/history_time.sh
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"


