- name: Take important system config backup and store on local disk. 
  script: "{{ role_path }}/files/linux_config_backup.sh"

- name: Take output of important system configuration in a file -PRE patching
  script: "{{ role_path }}/files/linux_output.sh >> /var/tmp/PRE_{{ ansible_hostname }}_system_info_output_{{ ansible_date_time.date }}.txt"
  register: system_out

- name: send system_info_output to a receipient through mail - PRE patching
  mail:
    host: localhost
    port: 25
    to: "{{ mail_recipient }}"
    subject: "PRE Patching - Linux server {{ ansible_hostname }} Ouput file"
    body: 'PRE PATCHING - System {{ ansible_hostname }} basic information file'
    attach: /var/tmp/PRE_{{ ansible_hostname }}_system_info_output_{{ ansible_date_time.date }}.txt
  when: system_out.rc == 0
