  

### cat playbook_cronlist.yml 

--- 

- name: Playbook - list crontabs of users 

  hosts: all 

  become: yes 

  

  vars: 

     CRONINFO: cronfiles_of_{{ ansible_hostname }}.txt 

  

  tasks: 

    - name: Task 1 - Checking contents of crontab files ...... 

      script: /etc/ansible/cronjob_info/croninfo.sh >> /var/tmp/{{ CRONINFO }} 

  

  

    - name: Task 2 - Fetching cronjob info to local server's '/var/tmp/croninfo' directory ..... 

      fetch: 

        src: /var/tmp/{{ CRONINFO }} 

        dest: /var/tmp/croninfo/{{ CRONINFO }} 

        flat: yes 

  

  

    - name: Task 3 - Creating a consolidated report under '/var/tmp/croninfo/report/' directory... 

      assemble: 

         src: /var/tmp/croninfo 

         dest: /var/tmp/croninfo/report/cronreport_allservers.txt 

         owner: myadmin 

         delimiter: '### ##### ##### ### #### #### ##### ###### ######' 

      run_once: true 

      delegate_to: localhost 

  

  

    - name: Task 4 - Cleaning up temporary files.......... 

      file: 

        path: /var/tmp/{{ CRONINFO }} 

        state: absent 

  
