### Generate password hash using python 

##  python -c 'import crypt,getpass; print crypt.crypt(getpass.getpass())' 

--- 
- hosts: all 
  gather_facts: false 

  vars: 
   - usernames: "{{ user_name_lists}}" 

  tasks: 
   - name: GetUserInfo 
     shell: egrep "^{{ item }}:" /etc/passwd 
     ignore_errors: yes 
     with_items: 
          - "{{ usernames }}" 
     register: user_info 


   - name: ChangeUserPassord 
     user: name="{{ item.item }}" password="{{ new_password }}" update_password=always 
     when: item.rc == 0 
     with_items: "{{ user_info.results }}" 

