---
### Playbook for disabling password authentication in sshd_config, which was enabled during EC2 deployment (see userdata)
### Run this playbook after Lab setup

- name: disable password authentication
  hosts: all
  become: yes

  tasks:
    - name: Disable password authentication in sshd_config file
      lineinfile:
         path: /etc/ssh/sshd_config
         state: present
         backup: yes
         regexp: '^PasswordAuthentication'
         line: PasswordAuthentication no
         validate: /usr/sbin/sshd -T -f %s
 
    - name: restart sshd service
      service: 
          name: sshd 
          state: restarted

## or you can use systemd module
##
##    - name: Reload sshd service
##      systemd: 
##            name: sshd
##            state: reloaded

### --------- To execute playbook, run below command -----
### $ ansible-playbook disable_password_based_auth.yml -i inventory -K
### BECOME password:

