---
### Playbook for disabling password authentication in sshd_config, which was enabled during EC2 deployment (see userdata)

- name: disable password authentication
  hosts: all
  become: yes

  tasks:
    - name: Disable password authentication in sshd_config file
      lineinfile:
         path: /etc/ssh/sshd_config
         backup: yes
         regexp: '^PasswordAuthentication'
         line: PasswordAuthentication no


### --------- To execute playbook, run below command -----
### $ ansible-playbook ssh_password_auth_no.yaml -i inventory -K
### BECOME password:

