--- 

- name: Add a line after a matching pattarn 

  hosts: all 

  become: yes 

  remote_user: myadmin 

   

  tasks: 

    - name: Inserting a line after a pattern match 

      lineinfile: 

        path: /etc/sudoers 

        state: present 

        backup: yes 

        line: Defaults:scom_local !requiretty 

        insertafter: Defaults    requiretty 

        validate: '/usr/sbin/visudo -cf %s' 

  

  

  

  

 