## cat port_check/remote_host_port_check.yml

---

- name: Playbook for checking port status on a remote host

  hosts: clientservers



  tasks:

    - name: Check all port numbers are accessible from current host

      wait_for:

          host: destinationserver.com

          port: "{{ item }}"

          state: started         # Port should be open 

          delay: 0               # No wait before first check (sec) 

          timeout: 3             # Stop checking after timeout (sec) 

      ignore_errors: yes

      with_items:

         - 22

         - 80

         - 443

